### ISSUE TITLE
`RunnerSet` terminates pods even when they are still running jobs

### ISSUE THREAD

**Issue by danxmoran** [actions-runner-controller/actions-runner-controller#1534] opened 2022-06-14 14:52 UTC
(Apologies for not using the bug template, I ran into #1533. Will attempt to recreate it)

### Controller Version
0.24.0

### Helm Chart Version
0.19.0

### CertManager Version
1.4.1

### Deployment Method
Helm

### cert-manager installation
Deploying `cert-manager` Helm chart from https://charts.jetstack.io

### Checks
- [x] Not a question / user support case
- [x] Read release notes
- [x] ARC version does support the feature
- [x] Already upgraded ARC

### Resource Definitions
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: clr-runner
  namespace: actions-runner-groups
spec:
  dockerdWithinRunnerContainer: false
  ephemeral: true
  labels:
  - clr-runner
  organization: color
  replicas: 1
  selector:
    matchLabels:
      app: clr-runner
  serviceName: clr-runner
  template:
    metadata:
      labels:
        app: clr-runner
    spec:
      containers:
      - image: 301643779712.dkr.ecr.us-east-1.amazonaws.com/color-actions-runner:master_c704c14c
        name: runner
        resources:
          limits:
            cpu: 8
            memory: 32Gi
          requests:
            cpu: 8
            memory: 32Gi
      - image: public.ecr.aws/docker/library/docker:dind
        name: docker
      securityContext:
        fsGroup: 1000
      serviceAccountName: actions-runner
      terminationGracePeriodSeconds: 1800
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: clr-runner
  namespace: actions-runner-groups
spec:
  maxReplicas: 30
  metrics:
  - scaleDownFactor: "0.7"
    scaleDownThreshold: "0.2"
    scaleUpFactor: "2.5"
    scaleUpThreshold: "0.5"
    type: PercentageRunnersBusy
  minReplicas: 1
  scaleDownDelaySecondsAfterScaleOut: 3600
  scaleTargetRef:
    kind: RunnerSet
    name: clr-runner
```

### To Reproduce
1. Wait for a job to start running on one of the pods in the `RunnerSet`
2. `kubectl -n actions-runner-groups delete pod <the-pod>`

### Describe the bug
The pod terminates immediately. The in-flight job is dropped, and appears to hang in the UI until it eventually times out (much later)

### Expected behavior
I expected `terminationGracePeriodSeconds: 1800` to prevent the pod from being forcibly shut down.

### Controller Logs
Will post in a follow-up comment

**Comment by danxmoran** [comment] 2022-06-14 14:55
Controller logs: [arc.log](https://github.com/actions-runner-controller/actions-runner-controller/files/8900895/arc.log)

**Comment by danxmoran** [comment] 2022-06-14 14:59
`Dockerfile` for the custom runner image we use:
```dockerfile
# NOTE: This file originally based on the instructions from
# https://github.com/actions-runner-controller/actions-runner-controller/blob/a62882d243fd8a3cd7901f72b99beeb92cc4e629/runner/actions-runner.dockerfile

FROM 301643779712.dkr.ecr.us-east-1.amazonaws.com/base-python:latest

ARG DUMB_INIT_VERSION=1.2.5
RUN URL="https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_x86_64" \
    && curl -fLo /usr/local/bin/dumb-init "${URL}" \
    && chmod +x /usr/local/bin/dumb-init

RUN apt-install-packages.sh sudo

ARG DOCKER_CHANNEL=stable
ARG DOCKER_VERSION=20.10.12
RUN URL="https://download.docker.com/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" \
    && curl -fLo docker.tgz "${URL}" \
    && tar zxvf docker.tgz \
    && install -o root -g root -m 755 docker/docker /usr/local/bin/docker \
    && rm -rf docker docker.tgz \
    && adduser --disabled-password --gecos "" --uid 1000 runner \
    && groupadd docker \
    && usermod -aG docker runner \
    && echo "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers

ENV HOME=/home/runner
ARG RUNNER_VERSION=2.292.0
ENV RUNNER_ASSETS_DIR=/runnertmp
# hadolint ignore=DL3003
RUN URL="https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz" \
    && mkdir -p "${RUNNER_ASSETS_DIR}" \
    && cd "${RUNNER_ASSETS_DIR}" \
    && curl -fLo runner.tar.gz "${URL}" \
    && tar xzf ./runner.tar.gz \
    && ./bin/installdependencies.sh \
    && mv ./externals ./externalstmp

ENV RUNNER_TOOL_CACHE=/opt/hostedtoolcache
RUN mkdir "${RUNNER_TOOL_CACHE}" \
    && chgrp docker "${RUNNER_TOOL_CACHE}" \
    && chmod g+rwx "${RUNNER_TOOL_CACHE}"

RUN apt-install-packages.sh amazon-ecr-credential-helper \
    && mkdir -p "${HOME}/.docker" \
    && echo '{"credsStore": "ecr-login"}' > "${HOME}/.docker/config.json" \
    && chown -R runner "${HOME}/.docker"

COPY src/infra/docker/snippets/install-awscli.sh /usr/local/bin/
RUN install-awscli.sh

RUN apt-install-packages.sh software-properties-common \
    && add-apt-repository -yn ppa:git-core/ppa \
    && apt-install-packages.sh git-core

ARG ACTIONS_RUNNER_SHA=ac27df83017e4cca65c5a712a6745428c3aec32a
RUN URL_PREFIX="https://raw.githubusercontent.com/actions-runner-controller/actions-runner-controller/${ACTIONS_RUNNER_SHA}/runner" \
    && curl -fLo /usr/local/bin/entrypoint.sh "${URL_PREFIX}/entrypoint.sh" \
    && curl -fLo /usr/local/bin/logger.bash "${URL_PREFIX}/logger.bash" \
    && chmod 755 /usr/local/bin/entrypoint.sh

ENV PATH="${PATH}:${HOME}/.local/bin"
ENV ImageOS=ubuntu20
RUN echo "PATH=${PATH}" > /etc/environment \
    && echo "ImageOS=${ImageOS}" >> /etc/environment

RUN sed -iE 'p; s/^deb /deb-src /' /etc/apt/sources.list \
    && apt-get update \
    && apt-get -y build-dep bedtools \
    && apt-install-packages.sh \
        bedtools \
        build-essential \
        jq \
        libcairo2 \
        libcurl4-openssl-dev \
        libpangocairo-1.0-0 \
        libpq-dev \
        libssl-dev \
        libzbar0 \
        libz-dev \
        postgresql-client

RUN git config --system --add safe.directory /color

USER runner

ENV PANTS_PYTHON_BOOTSTRAP_SEARCH_PATH="['<PATH>']"

ENTRYPOINT ["/usr/local/bin/dumb-init", "--", "entrypoint.sh"]
```

The base image it builds on top of is essentially `python:3.8`, but built on Ubuntu instead of Debian

**Comment by mumoshu** [comment] 2022-06-15 00:52
@danxmoran Hey! Could you confirm that it happens only when you manually deleted the pod like you explained in the reproduction steps? Then, it's working as intended anyway.

Our entrypoint.sh and apparently `actions/runner`, don't handle SIGTERM for graceful termination. Instead, we rely on ARC's controllers to call the runner unregistration GitHub API to ensure it's stopped before the pod is being deleted. `terminationGracePeriodSeconds` is the duration until the pod is SIGKILL'ed after SIGTERM. SIGTERM is sent to the pod immediately regardless of `terminationGracePeriodSeconds`, hence the behavior you observed.

**Comment by danxmoran** [comment] 2022-06-15 01:14
@mumoshu ah, I was manually deleting the pod as a quick test for the termination grace behavior - your explanation for why it doesn't work makes sense.

You mention that rolling updates are supposed to be tolerant of long-running jobs - I started down this path of investigation because we recently switched from RunnerDeployments to RunnerSets, and then started seeing pods get killed midway through running jobs when we updated the enclosing RunnerSet spec. Can you confirm that is unexpected behavior? If so I can set up the full repro with logs in a separate issue tomorrow morning.

I also tried setting the update policy to "OnDelete" as part of my investigation, but it didn't change the update behavior. I can file another issue for that too if it's unexpected.

Thanks!

**Comment by mumoshu** [comment] 2022-06-15 01:25
> Can you confirm that is unexpected behavior? If so I can set up the full repro with logs in a separate issue tomorrow morning.

Yep, that's an unexpected behavior!

In that case, it would be great if you could also share your `entrypoint.sh` referred from your Dockerfile.

Recently I have encountered that the use of an outdated entrypoint.sh resulted in passing `--once` instead of `--ephemeral` to the ephemeral runner's `actions/runner` agent, resulting in the terminating actions/runner to grab another job and ARC deletes the pod before the job completes. I doubt if your case is the same.

Note also that it's a variant of race conditions that ARC has fixed in recent few releases. Rolling updates should now be safe as long as everything is correctly configured.

Anyway, a brand-new issue with full information would be much appreciated! Thanks.

> I also tried setting the update policy to "OnDelete" as part of my investigation

In which resource you find update policy?

**Comment by danxmoran** [comment] 2022-06-15 02:27
> In which resource you find the update policy field?

I see it in the CRD definition for `RunnerSet` [here](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/config/crd/bases/actions.summerwind.dev_runnersets.yaml#L4226). I was able to set it and can see it in `kubectl get runnerset <name> -o yaml` output, but it doesn't seem to pass through to the underlying `StatefulSet` resources.

**Comment by mumoshu** [comment] 2022-06-15 02:33
@danxmoran Thanks! Gotcha, we must omit that field... RunnerSet manages one or more StatefulSets by itself so StatefulSet's updatePolicy doesn't make sense for RunnerSet anyway.

**Comment by danxmoran** [comment] 2022-06-15 02:50
Opened #1535 for the rolling update problem. Linked the `entrypoint.sh` there as well.

**Closed** 2022-06-15 02:51 UTC
