### ISSUE TITLE
Latest Runner Image Issues (summerwind/actions-runner@sha256:...4e48fc)

### ISSUE THREAD

**Issue by sbrinkerhoff** [actions-runner-controller/actions-runner-controller#1261] opened 2022-03-22 20:41 UTC
**Describe the bug**

About an hour ago I started getting odd actions executions ... Installing applications (awscli, etc) with pip are no longer on the path as they were about two hours ago.

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/323561/159571941-3f5be6f2-08c6-41db-8839-c5599a840205.png">

**Container Hashes**

Container that has issues with Python/PIP installed packages:

- container_hash:summerwind/actions-runner@sha256:8c0167b41f953d54f1dd48327bda7126a6ee27338ff285bb681fa91deb20cfd2

Previous container that was working ok:
- container_hash:summerwind/actions-runner@sha256:e4873556fba335c6f97e5b1613d70384ae55196c3b3721012cf3b4dec44e48fc

**References**

We probably picked up this change...

- https://github.com/actions-runner-controller/actions-runner-controller/commit/2cb04ddde7b89bf0de89d850aea433c0c2ad4ee5

**Comment by mumoshu** [comment] 2022-03-22 23:18
@sbrinkerhoff Hey! Thanks for reporting. Yes, I also suspect this is coming from 2cb04dd but not sure why- we didn't touch anything about PATH 🤔 

Do you have any idea where commands installed via pip, like `dynamodump`, are located at? Is it the case that previous versions of the runner image had that path in `$PATH` and currently it's doesn't for some reasons? 🤔

**Comment by BeyondEvil** [comment] 2022-03-22 23:31
I have a similar issue.

All of a sudden `/home/runner/.local/bin` is missing from `$PATH`, and our builds started failing 4 hours, which correlates exactly with the time `summerwind/action-runner` was updated.

I pulled the image locally and checked, and it's there. So something is weird.

Tomorrow I'll replace the `latest` tag with the previous one (the one published 8 days ago) to see the issue goes away.

I'm happy to provide more info.

**Comment by BeyondEvil** [comment] 2022-03-22 23:51
99% sure that the issue is with the actions-runner image.

The simples possible job, and `/home/runner/.local/bin` is missing from `$PATH`

![Screenshot 2022-03-23 at 00 49 24](https://user-images.githubusercontent.com/15611634/159595245-6dcd6a17-f0be-4675-903c-4c50b6446e66.png)

![Screenshot 2022-03-23 at 00 49 06](https://user-images.githubusercontent.com/15611634/159595254-561e94a2-3ba4-4861-9557-54b19eaf80f6.png)

**Comment by mumoshu** [comment] 2022-03-23 00:06
Thanks!

We previously `exec`ed into `runsvc.sh`:

https://github.com/actions-runner-controller/actions-runner-controller/blob/366f8927d8bd0cf0d53125cfc543cdc810846f21/runner/entrypoint.sh#L181

And it had this block of code to set `PATH` from the content of the `.path` file.
https://github.com/actions-runner-controller/actions-runner-controller/blob/366f8927d8bd0cf0d53125cfc543cdc810846f21/runner/patched/runsvc.sh#L7-L11

For me the `.path` file is located at `/runner/.path`: (Not sure who writes this file, but perhaps `actions/runner` does? 🤔 

```
runner@org-runnerdeploy-cfbdg-jqb97:/runner$ cat .path 
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runner/.local/bin
```

This seems to be missing in our code path which `exec` into `run.sh` instead of `runsvc.sh`:

https://github.com/actions-runner-controller/actions-runner-controller/blob/2cb04ddde7b89bf0de89d850aea433c0c2ad4ee5/runner/entrypoint.sh#L181

Now, the last missing piece for me is why it doesn't reproduce if we `docker run` or `kubectl exec` into the container with `/bin/bash` as an entry-point.

```
$ kubectl exec -it org-runnerdeploy-cfbdg-jqb97 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
runner@org-runnerdeploy-cfbdg-jqb97:/$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runner/.local/bin
```

Is there are way to let `bash` load PATH from the `.path` file? 🤔 

To me, it looks like all of `/etc/environment`, `/home/runner/.bashrc`, `/home/runner/.profile` and `/etc/profile` lack it. So I'm pretty confused why `/home/runner/.local/bin` is in `$PATH` if we run `bash` inside it while it isn't available to a workflow job run on it.

**Comment by BeyondEvil** [comment] 2022-03-23 00:27
So, it's confirmed now I think. With what you said @mumoshu and the fact that when I replaced `latest` with `v2.289.1-ubuntu-20.04-4cbbcd6`, the `$PATH` is correct again:

![Screenshot 2022-03-23 at 01 20 54](https://user-images.githubusercontent.com/15611634/159597936-f6a62d1f-6ac6-4898-a2bb-5130dd7cc226.png)

So, I might be wrong here, but based on [this](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile#L121-L122), when you run `docker run` (and maybe `kubectl exec`), with `/bin/bash` as entrypoint, it's not using `entrypoint.sh`.

Which I interpret as further proof that the issue is in `entrypoint.sh` or `run.sh`.

I'm not sure what exactly the purpose of the code-snippet from `runsvc.sh` is.

**Comment by mumoshu** [comment] 2022-03-23 00:40
@BeyondEvil Thanks for your confirmation. I run a few commands in the runner and verified that it might be due to our use of `mapfile` and `env` to compose the env passed to `run.sh`. We seem to have hidden the PATH loaded by bash with PATH defined in `/etc/environment`. The latter lacks `/home/runer/.local/bin` so that the problem occurs.

```
$ cat /etc/environment 
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

$ mapfile -t env </etc/environment

$ env -- "${env[@]}" | grep PATH
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

$ env -- "${env[@]}" bash -c 'env' | grep PATH
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
```

Still unsure how `bash` alone able to locate `/home/runner/.local/bin`, but perhaps we can just replicate controller/actions-runner-controller/blob/366f8927d8bd0cf0d53125cfc543cdc810846f21/runner/patched/runsvc.sh#L7-L11 in our entrypoint.sh as a quick fix.

**Comment by BeyondEvil** [comment] 2022-03-23 00:47
> Still unsure how `bash` alone able to locate `/home/runner/.local/bin`, but perhaps we can just replicate controller/actions-runner-controller/blob/366f8927d8bd0cf0d53125cfc543cdc810846f21/runner/patched/runsvc.sh#L7-L11 in our entrypoint.sh as a quick fix.

I would wager a guess that it's in `$PATH` _before_ running `entrypoint.sh`, because it's set in the Docker file [here](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile#L116) and then the mapfile/env stuff overwrites it.

So you can either replicate the runsvc.sh, or simply do what's done in the dockerfile: `PATH="${PATH}:${HOME}/.local/bin"`

Regardless, it's worth a try. 🤷‍♂️

**Comment by mumoshu** [comment] 2022-03-23 01:16
@BeyondEvil Ah thanks a lot! That explains the issue.

It might be like this; Since our recent introduction of the `mapfile` thing we forgot to tidy the `ENV PATH="${PATH}:${HOME}/.local/bin"` config in our Dockerfile.

It resulted in we unintentionally relied solely on the `.path` loader logic embedded in our legacy `runsvc.sh` to make pip-installed bins to work.

https://github.com/actions-runner-controller/actions-runner-controller/commit/2cb04ddde7b89bf0de89d850aea433c0c2ad4ee5 removed `runsvc.sh`, breaking things.

I remember that the introduction of `mapfile` thing was coming from the desired to let the user to customize runner environment without forking our runner image Dockerfile. So, the fix might need to be done in a way so that `/etc/environment` reflects the envvars set in our Dockerfile.

#1263 is the pull request. Would you mind taking a look? @BeyondEvil

**Comment by mumoshu** [comment] 2022-03-23 01:29
@BeyondEvil @sbrinkerhoff Would you mind giving it a shot once the new runner image has been automatically built and published after #1263 gets merged? Thanks!

**Closed** 2022-03-23 01:28 UTC

**Comment by BeyondEvil** [comment] 2022-03-23 08:47
Hey @mumoshu Sorry for ghosting, was way past my bedtime. :(

Anyway, it seems like it's working again (at least latest). Great work!

**Comment by mumoshu** [comment] 2022-03-23 23:03
@BeyondEvil Don't worry, your own life is the most important thing. And thanks for confirming! Glad to hear it's fixed ☺️

**Comment by matan-legit** [comment] 2024-02-14 05:38
is there a guide on how to use this image in the runner scale set helm chart

**Comment by matan-legit** [comment] 2024-02-14 05:38
is there a guide on how to use this image in the runner scale set helm chart

 @mumoshu
