### ISSUE TITLE
runners are not scaling up as per job count 

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#1238] opened 2022-03-17 14:01 UTC
**Describe the bug**
i am trigger 100 workflow job
i can see 100 runners created.
after some time 50 job will be pending to run
but that moment i can only see 5 to 10 runners avaialbe. and the workflow run will slow down and use only available runners.
am i missing something in the configuration.

```
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
github-actions-runner   actions-runner-system   5               2022-03-17 18:18:41.462305267 +0530 IST deployed        actions-runner-controller-0.17.0        0.22.0
```

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dot-runner
spec:
  template:
    spec:
      enterprise: xxxxx
      labels:
      - dot-enterprise-runner
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      image: rxxxxxxxx/actions-runner
      dockerEnabled: false
      securityContext:
        runAsUser: 1000
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
```

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
   name: ent-runner-auto-scaller
spec:
  scaleDownDelaySecondsAfterScaleOut: 5
  scaleTargetRef:
    name: dot-runner
  minReplicas: 1
  maxReplicas: 300
  scaleUpTriggers:
  - githubEvent: {}
    duration: "30m"
```

**Comment by toast-gear** [comment] 2022-03-17 19:59
Upgrade to v0.22.0, there were signficant changes to how scaling works in the latest release

**Comment by roshvin** [comment] 2022-03-18 04:39
Hi @toast-gear  we have already upgraded to v0.22.0

```
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
github-actions-runner   actions-runner-system   5               2022-03-17 18:18:41.462305267 +0530 IST deployed        actions-runner-controller-0.17.0        0.22.0
```

is there any change in runnerdeployment or HRA to tune as per the latest version.

**Comment by mumoshu** [comment] 2022-03-18 04:55
@roshvin Is your `scaleUpTriggers[].duration` enough for your use-case?

**Comment by roshvin** [comment] 2022-03-18 05:45
Hi @mumoshu  , thanks for your quick replay . could you pls suggest a number , i couldn't find much on the documentation. 
This runner is at our enterprise level and we may get lots of workflow jobs .

**Comment by mumoshu** [comment] 2022-03-18 05:59
@roshvin What's the longest duration between (1)the time the first job is enqueued and (2)the time the last job completes running? That should be the safest scaleTrigger duration.

**Comment by roshvin** [comment] 2022-03-18 06:38
Hi @mumoshu  , it will be like 2 Hrs when i test in INT  . but  in PROD since its enterprise level there is no last job ,  jobs will be keep on coming. 
we have 20K users and 50K repos . 
what would be your suggestion .

**Comment by mumoshu** [comment] 2022-03-18 06:40
> jobs will be keep on coming.

In my understanding, that's okay and unrelated to how long it should be.
Just set the longest duration between (1) and (2) for the longest workflow job that are intended to run on your runners tied to your HRA.

**Comment by roshvin** [comment] 2022-03-21 05:16
Hi @mumoshu  , thanks for the info . could you suggest you are referring to below value. 
 ```
 scaleUpTriggers:
  - githubEvent: {}
    duration: "30m"
```

also could you let us know  what below parameter do.

` scaleDownDelaySecondsAfterScaleOut: 5`

**Comment by genisd** [comment] 2022-03-22 12:06
> i was under impression that , if i have 50 jobs pending , there will be 50 runner at the moment.

It should, but sadly in case of an organizational runner there is no endpoint on githubs side as to how many jobs are pending(outstanding) on an organizational level to base the scaling on.

So it tries to scalup on webhook and scaledown once complete on same webhook.
It kind of works but it's far from perfect.

Your testing scenario is probably the arch enemy of current webhook scaling method and the underlying race conditions.
I'd be curious how your results look like if you did a random 1-3 minute jobs instead of 1s hello words.

**Comment by roshvin** [comment] 2022-03-22 12:54
@genisd thanks for you replay . i will try with 1 - 3 min job.
but our runner is not at Org level , Our runners are at Enterprise level and shared with Org

**Comment by genisd** [comment] 2022-04-06 13:23
I do face the same issue, that in rare occasions one ends up with unhandled jobs and no workers.
That starvation issue right now is the biggest obstacle that we are having ourselves as well with Organization workers + webhook driven scaling.

I would prefer to boot worker nodes based off webhooks, but *NOT* remove them from the webhooks and instead do that time based. That way I should not be facing any starvation issues right now ( I would think ).

**Comment by mumoshu** [comment] 2022-04-07 00:10
@roshvin Try a longer scaleUpTrigger duration. 30m means that the added desired replica gets removed 30 minutes after it received the `workflow_job` webhook event to queue it. It's not 30 minutes after the job started running so it needs to be very long. If your cluster is overloaded and it takes 3h in total to complete all the jobs, the scaleuptrigger duration should be longer than 3h.

**Comment by mumoshu** [comment] 2022-04-10 03:02
@genisd @roshvin Can we close this in favor of #1321?

**Comment by genisd** [comment] 2022-04-10 08:57
as far as i'm concerned yes.
#1321 is definitely the cause of this issue

**Closed** 2022-04-11 09:43 UTC
