### ISSUE TITLE
High API Calls quota consumption

### ISSUE THREAD

**Issue by Djiit** [actions-runner-controller/actions-runner-controller#1101] opened 2022-02-08 17:48 UTC
**Describe the bug**

Hey folks,

Thanks for this awesome controller.

We recently had really high GitHub API quota consumption on our runner pool managed with this controller.

**Checks**

- [x] My actions-runner-controller version (v0.20.4) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

When scaling to 100+ replicas, we're starting to see a very high amount of API calls. Not sure it's related tho; but our workflows didn't change (no rogue job looping on a github call).
- Could it be them, our "idle" runners, that are constantly polling the API ?
- Is there a known stability limit of # of replicas?
- Did we get anything wrong?

**Expected behavior**

We expected our runner pools to scale OK with the load, and were planning on adding another controller with a separate Github App to balance the API usage. Well, the wall came earlier.

**Screenshots**

Our workload is roughly the same:
![image](https://user-images.githubusercontent.com/1169844/153044488-88ab5e8c-819d-4ab2-ae34-a577e12e3b46.png)

When we hit the quota limit, well, we had a queuing spike:
![image](https://user-images.githubusercontent.com/1169844/153044669-cb3337f5-9d85-475c-b39a-213c979a016b.png)

But overall it was a "normal" day; except the huge spike in quota consumption: 
<img width="494" alt="Capture d’écran 2022-02-08 à 18 39 53" src="https://user-images.githubusercontent.com/1169844/153044846-30d29b1f-4a47-4ad5-a191-9f8ffc9e2c59.png">

You can notice at the right part of this graph above that we added more controllers with their own Github App (1 to 100 replicas each), trying to ease the pain.. But nope, both of them were consumed very quickly.

FTR, here is what a normal day (used to) look like : 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/1169844/153046146-46f7064d-d9dc-4991-9fc0-eb632e843331.png">

**Environment (please complete the following information):**
 - Controller Version: 0.20.4
 - Deployment Method: vanilla YAML apply
 - Running on EKS 1.20
 - Using Organization runners

**Additional context**

Our current setup is the following:

- 1 EKS clusters
- 3 actions-runner-controllers in 3 different namespaces (different labels are applied on the runners, depending on the controller).
- using the same runner groups (is it an (scaling) issue?)

**Comment by mumoshu** [comment] 2022-02-09 00:09
@Djiit Hey! Thanks for reporting. I believe this is dupe of https://github.com/actions-runner-controller/actions-runner-controller/issues/920 so let us consolidate into that to better accumulate all the information related to the issue.

**Closed by mumoshu** 2022-02-09 00:09 UTC

**Comment by Djiit** [comment] 2022-02-09 15:11
I can confirm capping our replicas to ~75 is really helping.
