### ISSUE TITLE
HPA issue

### ISSUE THREAD

**Issue by ajaychoudhary-hotstar** [actions-runner-controller/actions-runner-controller#1070] opened 2022-01-24 06:44 UTC
**Describe the bug**
We have two installations for GitHub actions with HPA. When the HPA event triggers repo 1, sometimes it doesn't scale pod. Sometimes if it scales then some other actions pick it and run, But the PR webhook event which triggered the HPA event doesn't get any pod. Please help with this. How we can make sure we autoscale +1 on every queue event and scale down -1 on every completed event. How we can make sure if Repo 1 Webhook triggered event it should run repo 1 action only. 

**Checks**

- [ ] v0.20.3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version v0.20.3
 - Deployment Method [e.g. Helm and Kustomize ] Helm
 - Helm Chart Version [e.g. 0.11.0, if applicable] 0.14.0

**Additional context**

apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name:  "{{ .Values.runner.name }}-ci"
  namespace: {{ .Release.Namespace }}
spec:
  scaleDownDelaySecondsAfterScaleOut: 5
  minReplicas: 0
  maxReplicas: 100
  scaleTargetRef:
    name: "{{ .Values.runner.name }}-ci"
  scaleUpTriggers:
  - githubEvent: {}
    duration: "20m"

**Comment by mumoshu** [comment] 2022-01-24 06:48
@ajaychoudhary-hotstar Hey. Could you provide full details?

- Number of repositories, Names of those repositories
- All the RunnerDeployments
- All the HRAs

**Comment by ajaychoudhary-hotstar** [comment] 2022-01-24 07:11
@mumoshu We have around 25+ repos, difficult to share names here, 
Two runners deployments
 
Two HPA Deployments 
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: "{{ .Values.runner.name }}-ci"
  namespace: {{ .Release.Namespace }}
  labels:
    team: {{ .Values.organization.teamName }}
spec:
  template:
    metadata:  
      annotations:
        iam.amazonaws.com/role: {{ .Values.iam_role_arn }}
      labels:
        team: {{ .Values.organization.teamName }}
    spec:
      terminationGracePeriodSeconds: 120
      serviceAccountName: {{ .Values.serviceAccount.name }}
      image: "{{ .Values.image.repository }}"
      env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"  
      resources:
        limits:
          ephemeral-storage:  {{ .Values.resources.medium.limits.ephemeral_storage }}
        requests:
          cpu: {{ .Values.resources.medium.requests.cpu }}
          memory: {{ .Values.resources.medium.requests.memory }}
          ephemeral-storage:  {{ .Values.resources.medium.requests.ephemeral_storage }}
      tolerations:
        - key: {{ .Values.tolerations.key }}
          operator: {{ .Values.tolerations.operator }}
          value: {{ .Values.tolerations.value }}
          effect: {{ .Values.tolerations.effect }} 
      dockerdWithinRunnerContainer: true
      organization: {{ .Values.organization.organizationName }}
      labels:
        - {{ .Values.runner.runner_label_ci }}
      group: {{ .Values.organization.Group }}
     
     HPA:
     
     apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
name: "{{ .Values.runner.name }}-ci"
namespace: {{ .Release.Namespace }}
spec:
scaleDownDelaySecondsAfterScaleOut: 5
minReplicas: 0
maxReplicas: 100
scaleTargetRef:
name: "{{ .Values.runner.name }}-ci"
scaleUpTriggers:

githubEvent: {}
duration: "20m"

Second deployment
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.runner.name }}
  namespace: {{ .Release.Namespace }}
  labels:
   team: {{ .Values.organization.teamName }}
spec:
  template:
    metadata:  
      annotations:
        iam.amazonaws.com/role: {{ .Values.iam_role_arn }}
      labels:
        team: {{ .Values.organization.teamName }}
    spec:
      terminationGracePeriodSeconds: 120
      serviceAccountName: {{ .Values.serviceAccount.name }}
      image: "{{ .Values.image.repository }}"
      env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"  
      resources:
        limits:
          cpu: {{ .Values.resources.small.limits.cpu }}
          memory: {{ .Values.resources.small.limits.memory }}
          ephemeral-storage:  {{ .Values.resources.small.limits.ephemeral_storage }}
        requests:
          cpu: {{ .Values.resources.small.requests.cpu }}
          memory: {{ .Values.resources.small.requests.memory }}
          ephemeral-storage:  {{ .Values.resources.small.requests.ephemeral_storage }}
      tolerations:
        - key: {{ .Values.tolerations.key }}
          operator: {{ .Values.tolerations.operator }}
          value: {{ .Values.tolerations.value }}
          effect: {{ .Values.tolerations.effect }}  
      dockerdWithinRunnerContainer: true
      organization: {{ .Values.organization.organizationName }}
      labels:
        - {{ .Values.runner.runner_label }}
      group: {{ .Values.organization.Group }}
     
     HPA:
     apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: "{{ .Values.runner.name }}"
  namespace: {{ .Release.Namespace }}
spec:
  scaleDownDelaySecondsAfterScaleOut: 120
  minReplicas: 0
  maxReplicas: 100
  scaleTargetRef:
    name: {{ .Values.runner.name }}
  scaleUpTriggers:
  - githubEvent: {}
    duration: "20m"

**Comment by mumoshu** [comment] 2022-01-24 07:30
> We have around 25+ repos, difficult to share names here,
> Two runners deployments
> ...
> organization: {{ .Values.organization.organizationName }}
> ...
> labels:
> - {{ .Values.runner.runner_label }}
>...
> labels:
> - {{ .Values.runner.runner_label_ci }}

ARC seems to be doing what you asked.
Assuming all your RunnerDeployment specs and HRA specs are configured as you intended,

> sometimes it doesn't scale pod. Sometimes if it scales then some other actions pick it and run, But the PR webhook event which triggered the HPA event doesn't get any pod

You might have misunderstood how ARC works.
ARC has no way to "force assignment" of a pending workflow job to a specific (newly created) runner.
ARC adds runners as requested, GitHub assigns runners (like randomly) to queued workflow jobs.

I see `duration: "20m"`, which means you want to keep the added runner replica only for 20 minutes.
If your workflow job occasionally takes more time than 20 minutes it's problematic- try longer `duration` so that ARC could keep the added replicas until it finishes.

Please read https://github.com/actions-runner-controller/actions-runner-controller/issues/1044#issuecomment-1009741357.
We're living in an eventually consistent world so ARC doesn't rely on the quite untrue fact that webhook delivery is 100% guaranteed.

**Comment by ajaychoudhary-hotstar** [comment] 2022-01-24 08:28
@mumoshu We set that to 60 min as well but didn't help. How do we make sure we scale on every queue event and scale down on every completed event?

**Comment by mumoshu** [comment] 2022-01-24 09:49
> we scale on every queue event and scale down on every completed event?

@ajaychoudhary-hotstar 60 mins should be enough to make it work like that, assuming your workflow job never takes more than 60 minuets in practice.

**Comment by ajaychoudhary-hotstar** [comment] 2022-01-24 13:05
@mumoshu Job takes a max of 5-6 minutes. Even after making it 60 min, we are facing the same issue.

**Comment by mumoshu** [comment] 2022-01-24 23:39
@ajaychoudhary-hotstar Well, ARC doesn't match runner to workflow job one by one. That's impossible to be done perfectly due to the lack of GitHub APIs for that. What we do instead is to try to calculate the desired number of runners per enteprise/organization/repo depending on the recently received webhook events. 

So

> When the HPA event triggers repo 1, sometimes it doesn't scale pod.

This is completely valid when e.g. one replica added via a `queued` workflow_job webhook event while one replica removed due to a capacity reservation expiration at the same time.

> Sometimes if it scales then some other actions pick it and run, But the PR webhook event which triggered the HPA event doesn't get any pod

This might be caused by your misunderstanding. ARC should provide approximately enough runners that are demanded at that time. A newly added runner won't be 100% assigned to the latest workflow_job(because that's uncontrollable). It can still be assigned to another, already created runner though.

**Comment by mumoshu** [comment] 2022-01-24 23:41
That said, you'll be able to monitor if your autoscaling setup is working correctly only by tracking the time each workflow_job takes to transition from `queued` to `in_progerss`.

**Comment by mumoshu** [comment] 2022-01-24 23:44
> we scale on every queue event and scale down on every completed event?

Again, this isn't what you should ask for. The current GitHub Actions API doesn't allow us to implement that correctly.

But ARC's autoscaling does provide the ability to retain the number of desired runners demanded at the time, so your workflow job will get scheduled quickly enough as long as you've configured ARC correctly.

**Comment by ajaychoudhary-hotstar** [comment] 2022-01-25 13:00
> But ARC's autoscaling does provide the ability to retain the number of desired runners demanded at the time, so your workflow job will get scheduled quickly enough as long as you've configured ARC correctly.

How we can configure ARC correctly. Could you please share that? Or current setup looks fine?

**Comment by mumoshu** [comment] 2022-01-26 00:50
@ajaychoudhary-hotstar Yeah, your configuration looks fine alone. In other words, I can't say if your configuration is correct without seeing all your organization, repositories, and workflow definitions.

If it doesn't work as you might have expected, you either misunderstood how ARC works, or have misconfiguration that I can't see from the manifests alone.

If you really see ARC scaling the wrong set of runners, please double-check if you correctly set runner labels on RunnerDeployment and also you have listed correct labels under `on` of your workflow definitions.

Sorry but I'm closing this, as it doesn't look like a bug even though you used the format of a bug report.
But please feel free to file a bug report if you could come up with a concrete reproduction procedure.

**Closed by mumoshu** 2022-01-26 00:50 UTC

**Comment by mumoshu** [comment] 2022-01-26 00:51
BTW the right place to have community support would be to use GitHub Discussions!
