### ISSUE TITLE
webhook server: "cache contained <nil>, which is not an Object" when handling check_run event

### ISSUE THREAD

**Issue by invakid404** [actions-runner-controller/actions-runner-controller#776] opened 2021-08-30 12:55 UTC
**Describe the bug**
When receiving a check_run event, the webhook server throws an error, which states the following:
```
ERROR controllers.Runner handling check_run event {"event": "check_run", "hookID": "xxxxxxxxx", "delivery": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "checkRun.status": "completed", "action": "completed", "error": "cache contained <nil>, which is not an Object"}
```

**Checks**

- [x] My actions-runner-controller version (v0.19.0) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Follow the install guide
2. Configure the Helm chart to start the Webhook server, expose it
3. Create a webhook in GitHub to listen for `check_run` events
4. Run a workflow to trigger an event
5. Observe the error in the Webhook server's logs

**Expected behavior**
I've configured a HorizontalRunnerAutoscaler to scale on a `check_run` event, so the expected behavior is for a new runner to be spun up.

**Environment (please complete the following information):**
 - Controller Version: 0.19.0
 - Deployment Method: Helm
 - Helm Chart Version: 0.12.7

**Additional context**
I've authenticated via an app with the following permissions:
```
Actions (read)
Checks (read)
Metadata (read)
Self-hosted runners (read / write)
```

This is the runner configuration I'm using:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: senteca-runner
spec:
  template:
    spec:
      organization: senteca
      dockerdWithinRunnerContainer: true
      env:
        - name: STARTUP_DELAY_IN_SECONDS
          value: "10"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: senteca-runner-autoscaler
spec:
  scaleTargetRef:
    name: senteca-runner
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 0
  maxReplicas: 5
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 1
    duration: "5m"
```

This is how my GitHub webhook looks like:
![image](https://user-images.githubusercontent.com/38114607/131342081-916b7603-c8cf-47be-9197-8b5a44886467.png)

Any hints as to what may be wrong on my end are welcome. Thanks in advance :^)

**Comment by invakid404** [comment] 2021-08-30 12:57
Here's the full stacktrace from the log:
```
2021-08-30T12:53:20.820484530Zgithub.com/go-logr/zapr.(*zapLogger).Error
Error
2021-08-30T12:53:20.820493882Z /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
Error
2021-08-30T12:53:20.820502358Zgithub.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle
Error
2021-08-30T12:53:20.820511166Z /workspace/controllers/horizontal_runner_autoscaler_webhook.go:207
Error
2021-08-30T12:53:20.820519214Znet/http.HandlerFunc.ServeHTTP
Error
2021-08-30T12:53:20.820527102Z /usr/local/go/src/net/http/server.go:2042
Error
2021-08-30T12:53:20.820535191Znet/http.(*ServeMux).ServeHTTP
Error
2021-08-30T12:53:20.820542990Z /usr/local/go/src/net/http/server.go:2417
Error
2021-08-30T12:53:20.820550877Znet/http.serverHandler.ServeHTTP
Error
2021-08-30T12:53:20.820558196Z /usr/local/go/src/net/http/server.go:2843
Error
2021-08-30T12:53:20.820566004Znet/http.(*conn).serve
Error
2021-08-30T12:53:20.820574036Z /usr/local/go/src/net/http/server.go:1925```
Hope it's useful.

**Comment by mumoshu** [comment] 2021-08-31 21:02
@invakid404 Hey! Thanks for reporting.

This is coming from controller-runtime which is the library we're using under the hood.

And the error seems to be coming from:

https://github.com/kubernetes-sigs/controller-runtime/blob/4e7f0c968b90a306fb9ef22f8e92fa36b98b4ef1/pkg/cache/internal/cache_reader.go#L81

That said, I have no idea how I could make it happen. Perhaps your Kubernetes installation is special? This never happened on my env and I have never heard anyone encountering this, at least.

Which Kubernetes version are you using? Are you on AWS, Azure, GCP, or on-prem? Could you share your deployment of actions-runner-controller, by running `kubectl get deploy -o yaml` on your controller-manager deployment?

**Comment by invakid404** [comment] 2021-08-31 21:07
Hello, thank you for replying. I'm on GCP, running Kubernetes `1.20.8-gke.900`. For some reason, `kubectl get deploy -o yaml` doesn't output anything interesting:
![image](https://user-images.githubusercontent.com/38114607/131575755-a8c06ad3-4a59-4ae2-9fdd-08e8fc37940e.png)
This is the YAML of actions-runner-controller according to GCP though, hope it's the right one:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: actions-runner-controller
    meta.helm.sh/release-namespace: actions-runner-system
  creationTimestamp: "2021-08-30T09:22:24Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: actions-runner-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/version: 0.19.0
    helm.sh/chart: actions-runner-controller-0.12.7
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app.kubernetes.io/instance: {}
              f:app.kubernetes.io/name: {}
          f:spec:
            f:containers:
              k:{"name":"kube-rbac-proxy"}:
                .: {}
                f:args: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8443,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:securityContext: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
              k:{"name":"manager"}:
                .: {}
                f:args: {}
                f:command: {}
                f:env:
                  .: {}
                  k:{"name":"GITHUB_APP_ID"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                        f:optional: {}
                  k:{"name":"GITHUB_APP_INSTALLATION_ID"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                        f:optional: {}
                  k:{"name":"GITHUB_APP_PRIVATE_KEY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"GITHUB_TOKEN"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                        f:optional: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":9443,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:securityContext: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/etc/actions-runner-controller"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
                  k:{"mountPath":"/tmp"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/tmp/k8s-webhook-server/serving-certs"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"cert"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:secretName: {}
              k:{"name":"secret"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:secretName: {}
              k:{"name":"tmp"}:
                .: {}
                f:emptyDir: {}
                f:name: {}
    manager: helm
    operation: Update
    time: "2021-08-30T09:22:24Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-08-31T09:14:03Z"
  name: actions-runner-controller
  namespace: actions-runner-system
  resourceVersion: "563347"
  uid: 77d00890-48c3-42fe-b036-235d1012b32c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: actions-runner-controller
      app.kubernetes.io/name: actions-runner-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: actions-runner-controller
        app.kubernetes.io/name: actions-runner-controller
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --sync-period=10m
        - --docker-image=docker:dind
        - --runner-image=summerwind/actions-runner:latest
        command:
        - /manager
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: github_token
              name: controller-manager
              optional: true
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              key: github_app_id
              name: controller-manager
              optional: true
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              key: github_app_installation_id
              name: controller-manager
              optional: true
        - name: GITHUB_APP_PRIVATE_KEY
          value: /etc/actions-runner-controller/github_app_private_key
        image: summerwind/actions-runner-controller:v0.19.0
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/actions-runner-controller
          name: secret
          readOnly: true
        - mountPath: /tmp
          name: tmp
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: quay.io/brancz/kube-rbac-proxy:v0.10.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: metrics-port
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: actions-runner-controller
      serviceAccountName: actions-runner-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - name: secret
        secret:
          defaultMode: 420
          secretName: controller-manager
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      - emptyDir: {}
        name: tmp
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-30T09:32:51Z"
    lastUpdateTime: "2021-08-30T09:32:51Z"
    message: ReplicaSet "actions-runner-controller-5fd4894c95" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-08-31T09:14:03Z"
    lastUpdateTime: "2021-08-31T09:14:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1```

**Comment by mumoshu** [comment] 2021-08-31 21:48
@invakid404 Hey! Thanks for sharing. Your deployment seems good. Then my only suggestion would be to try deleting all the actions-runner-controller-related resources(perhaps by running `helm delete`) and then reinstalling everything from scratch.

**Comment by invakid404** [comment] 2021-08-31 21:49
Hmm, I'll give it a try ASAP and I'll update you.

**Comment by nicon89** [comment] 2021-09-01 15:39
I'm having same issue on AKS 1.19.11:
```
2021-09-01T15:38:35.916Z        ERROR   controllers.Runner      handling check_run event        {"event": "push", "hookID": "315999603", "delivery": "ab6b1bb8-0b3a-11ec-87ce-a32ea0127454", "error": "cache contained <nil>, which is not an Object"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle
        /workspace/controllers/horizontal_runner_autoscaler_webhook.go:207
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2042
net/http.(*ServeMux).ServeHTTP
        /usr/local/go/src/net/http/server.go:2417
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1925
2021-09-01T15:38:36.017Z        DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "webhookbasedautoscaler", "request": "actions-runner-system/runner-kaniko-autoscaler"}
2021/09/01 15:38:51 http: superfluous response.WriteHeader call from github.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle.func1 (horizontal_runner_autoscaler_webhook.go:82)
```

**Comment by invakid404** [comment] 2021-09-01 18:40
@mumoshu I tried on a whole new cluster, followed the readme, same exact error. And apparently I'm not alone now...

**Comment by mumoshu** [comment] 2021-09-05 23:48
Thanks for testing- Interesting. I will try to reproduce it on my env when I have some spare time.

**Comment by mumoshu** [comment] 2021-09-05 23:48
@nicon89 Hey! Thanks for adding your comment. To be extra sure, what was your exact controller version and chart version? Also, does it happen 100% of the time it receives a webhook request?

**Comment by nicon89** [comment] 2021-09-06 08:24
I'm using chart version 0.12.8.
It's hard to tell if it's 100% of time, but I believe so. I tested it one more time and I'm getting same error:
```
2021-09-06T08:22:22.824Z        ERROR   controllers.Runner      handling check_run event        {"event": "push", "hookID": "315999603", "delivery": "8f204604-0eeb-11ec-832d-cee420d5c079", "error": "cache contained <nil>, which is not an Object"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle
        /workspace/controllers/horizontal_runner_autoscaler_webhook.go:207
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2042
net/http.(*ServeMux).ServeHTTP
        /usr/local/go/src/net/http/server.go:2417
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1925
```

**Comment by mumoshu** [comment] 2021-09-06 08:32
@nicon89 Could you try downgrading actions-runner-controller-related CRDS to CRD v1beta1 instead of v1 that bumped in https://github.com/actions-runner-controller/actions-runner-controller/commit/9e4dbf497cc0cf1c7eb5cd4122d1e909145dbadc#diff-158ea5cd0bcb091351a324cb04fd035cda472625e9c2ea293857bffb89cde4dd ?

The chart version 0.12.2 or less uses the older CRD API that may related to this issue.

**Comment by nicon89** [comment] 2021-09-06 09:38
@mumoshu same issue.
```
$ k api-resources |grep summerwi
horizontalrunnerautoscalers       hra                actions.summerwind.dev/v1alpha1       true         HorizontalRunnerAutoscaler
runnerdeployments                 rdeploy            actions.summerwind.dev/v1alpha1       true         RunnerDeployment
runnerreplicasets                 rrs                actions.summerwind.dev/v1alpha1       true         RunnerReplicaSet
runners                                              actions.summerwind.dev/v1alpha1       true         Runner
runnersets                                           actions.summerwind.dev/v1alpha1       true         RunnerSet
```
```
2021-09-06T09:37:19.761Z        ERROR   controllers.Runner      handling check_run event        {"event": "push", "hookID": "315999603", "delivery": "07774fc6-0ef6-11ec-9e02-359ed5f72b13", "error": "cache contained <nil>, which is not an Object"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle
        /workspace/controllers/horizontal_runner_autoscaler_webhook.go:207
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2042
net/http.(*ServeMux).ServeHTTP
        /usr/local/go/src/net/http/server.go:2417
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1925
2021/09/06 09:37:35 http: superfluous response.WriteHeader call from github.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle.func1 (horizontal_runner_autoscaler_webhook.go:82)
2021-09-06T09:37:37.340Z        DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "webhookbasedautoscaler", "request": "actions-runner-system/runner-kaniko-autoscaler"}
2021/09/06 09:37:37 http: superfluous response.WriteHeader call from github.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle.func1 (horizontal_runner_autoscaler_webhook.go:82)
```

**Comment by mumoshu** [comment] 2021-09-06 09:45
@nicon89 Thanks! That's super interesting. Let me think for a while. In the meantime, I'd appreciate it if you could also share any information that you think is relevant(if any)

**Comment by nicon89** [comment] 2021-09-06 09:51
I'm not sure if it's relevant, but I can see that crds in both versions 0.12.2 and 0.12.8 are v1alpha1:
```
nicon@5CG10725TV-W10:.../git/aks-da-its-eastus2-dev-cluster-admin$ k api-resources |grep summerwi
horizontalrunnerautoscalers       hra                actions.summerwind.dev/v1alpha1       true         HorizontalRunnerAutoscaler
runnerdeployments                 rdeploy            actions.summerwind.dev/v1alpha1       true         RunnerDeployment
runnerreplicasets                 rrs                actions.summerwind.dev/v1alpha1       true         RunnerReplicaSet
runners                                              actions.summerwind.dev/v1alpha1       true         Runner
runnersets                                           actions.summerwind.dev/v1alpha1       true         RunnerSet
nicon@5CG10725TV-W10:.../git/aks-da-its-eastus2-dev-cluster-admin$ helm list
NAME                            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
actions-runner-controller       actions-runner-system   2               2021-09-01 13:01:15.4505454 +0200 CEST  deployed        actions-runner-controller-0.12.8        0.19.0
```

```
nicon@5CG10725TV-W10:.../git/aks-da-its-eastus2-dev-cluster-admin$ helm list
NAME                            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
actions-runner-controller       actions-runner-system   3               2021-09-06 11:32:43.6240127 +0200 CEST  deployed        actions-runner-controller-0.12.2        0.19.0
nicon@5CG10725TV-W10:.../git/aks-da-its-eastus2-dev-cluster-admin$ k api-resources |grep summerwi
horizontalrunnerautoscalers       hra                actions.summerwind.dev/v1alpha1       true         HorizontalRunnerAutoscaler
runnerdeployments                 rdeploy            actions.summerwind.dev/v1alpha1       true         RunnerDeployment
runnerreplicasets                 rrs                actions.summerwind.dev/v1alpha1       true         RunnerReplicaSet
runners                                              actions.summerwind.dev/v1alpha1       true         Runner
runnersets                                           actions.summerwind.dev/v1alpha1       true         RunnerSet
```

**Comment by nicon89** [comment] 2021-09-09 16:19
@mumoshu: is there any update on this?

**Comment by mumoshu** [comment] 2021-09-09 23:35
@nicon89 No. I've been busy these days and unfortunately had no spare time to spend time debugging this 😢

**Comment by kszymans** [comment] 2021-09-23 11:39
In my case I had to delete github-webhook-server pod. After restart it started working.

**Comment by peimanja** [comment] 2021-09-23 17:35
also started seeing this with chart v0.13.0 and controller v0.20.0:
```
021-09-22T21:49:08.221Z	INFO	controllers.Runner	finding organizational runner	{"event": "workflow_job", "hookID": "290639658", "delivery": "e98f45d0-1bee-11ec-8b9e-dbe85cf41894", "workflowJob.status": "queued", "workflowJob.labels": ["feature/generic", "size/nano", "env/infra-mgmt", "group/default"], "repository.name": "gitops-qa", "repository.owner.login": "<my-org>", "repository.owner.type": "Organization", "action": "queued", "organization": "<my-org>"}
2021-09-22T21:49:08.221Z	ERROR	controllers.Runner	handling check_run event	{"event": "workflow_job", "hookID": "290639658", "delivery": "e98f45d0-1bee-11ec-8b9e-dbe85cf41894", "workflowJob.status": "queued", "workflowJob.labels": ["feature/generic", "size/nano", "env/infra-mgmt", "group/default"], "repository.name": "gitops-qa", "repository.owner.login": "<my-org>", "repository.owner.type": "Organization", "action": "queued", "error": "cache contained <nil>, which is not an Object"}
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2046
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2424
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2878
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1929
```
Restarting the pods solved it for the time being

**Comment by nicon89** [comment] 2021-09-27 11:48
I confirm that restarting pod helped me with this issue as well.

**Comment by sledigabel** [comment] 2021-11-04 09:45
I'm seeing this problem as well, the `cache container <nil>` error happens after a while (not sure why?) and then the webhook services need restarting as they stop handling hooks correctly and autoscaling is broken.

**Comment by mumoshu** [comment] 2021-11-05 00:43
Thanks, everyone! I tracked it down to some code in client-go:

https://github.com/kubernetes-sigs/controller-runtime/blob/6c7c1d73fc5ed965c2962d6f4552b15f9841ce86/pkg/cache/internal/cache_reader.go#L81

The comment says `This should never happen` and I have no clue what's causing this. If anyone could provide me reliable reproduction steps that would help a lot.

**Comment by sledigabel** [comment] 2021-11-18 09:56
I've just seen it reappear, and it was straight after deleting a runnerdeployment and its matching HRA.
Perhaps it's to do with deleting an object and the webhook service not handling it properly?

**Comment by erichorwath** [comment] 2021-11-19 19:04
> In my case I had to delete github-webhook-server pod. After restart it started working.
same for us.
`cache contained <nil>` occurred when deleting a runnerDeployment+HRA and recreating it in a different namespace.
Chart: 0.14.0, app: 0.20.2

**Comment by mumoshu** [comment] 2022-04-13 23:15
We've upgraded controller-runtime and other dependencies several times since then. If it reproduced, we can't say for sure if the cause is the same. I'm closing this as resolved because we have not received any issues like this recently. Please feel free to submit another issue if necessary

**Closed by mumoshu** 2022-04-13 23:15 UTC
Labels: bug, help wanted
