### ISSUE TITLE
Runner pods sometimes get stuck in a crashloop 

### ISSUE THREAD

**Issue by cspargo** [actions-runner-controller/actions-runner-controller#1304] opened 2022-04-05 10:16 UTC
**Describe the bug**
Runner pods sometimes crashloop and never recover. The runner appears to have been deregistered, but the pod never gets deleted and gets stuck in crashloop, although it can never work because it's not registered.

The crashlooping pod also stops scaleup from happening (using PercentageRunnersBusy).

**To Reproduce**
Happens randomly. Not sure what triggers it.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version 0.22.2
 - Deployment Method Helm
 - Helm Chart Version 0.17.2

Partial log from controller

```
2022-04-05T09:06:02Z    INFO    runner-resource validate resource to be created {"name": "org-xxx-gg9z5-knxg4"}
2022-04-05T09:06:02Z    DEBUG   actions-runner-controller.runnerreplicaset      Skipped reconcilation because owner is not synced yet   {"runnerreplicaset": "actions-runner/org-xxx-gg9z5", "owner": "actions-runner/org-xxx-gg9z5-knxg4", "pods": null}
2022-04-05T09:06:02Z    INFO    runner-resource validate resource to be updated {"name": "org-xxx-gg9z5-knxg4"}
2022-04-05T09:06:02Z    INFO    actions-runner-controller.runner        Updated registration token      {"runner": "org-xxx-gg9z5-knxg4", "repository": ""}
2022-04-05T09:06:02Z    DEBUG   events  Normal  {"object": {"kind":"Runner","namespace":"actions-runner","name":"org-xxx-gg9z5-knxg4","uid":"bbea1ce0-f723-47ff-bca7-c899ce94962c","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"405522972"}, "reason": "RegistrationTokenUpdated", "message": "Successfully update registration token"}
2022-04-05T09:06:02Z    DEBUG   actions-runner-controller.runnerreplicaset      Skipped reconcilation because owner is not synced yet   {"runnerreplicaset": "actions-runner/org-xxx-gg9z5", "owner": "actions-runner/org-xxx-gg9z5-knxg4", "pods": null}
2022-04-05T09:06:03Z    INFO    actions-runner-controller.runner        Created runner pod      {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "repository": ""}
2022-04-05T09:06:03Z    DEBUG   events  Normal  {"object": {"kind":"Runner","namespace":"actions-runner","name":"org-xxx-gg9z5-knxg4","uid":"bbea1ce0-f723-47ff-bca7-c899ce94962c","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"405522977"}, "reason": "PodCreated", "message": "Created pod 'org-xxx-gg9z5-knxg4'"}
2022-04-05T09:06:05Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:06:05Z    ERROR   actions-runner-controller.runnerreplicaset      Failed to patch owner to have actions-runner/unregistration-request-timestamp annotation        {"runnerreplicaset": "actions-runner/org-xxx-gg9z5", "lastSyncTime": "2022-04-05T09:06:02Z", "effectiveTime": "<nil>", "templateHashDesired": "84876f64db", "replicasDesired": 19, "replicasPending": 1, "replicasRunning": 19, "replicasMaybeRunning": 20, "templateHashObserved": ["84876f64db"], "owner": "actions-runner/org-xxx-gg9z5-knxg4", "error": "Operation cannot be fulfilled on runners.actions.summerwind.dev \"org-xxx-gg9z5-knxg4\": the object has been modified; please apply your changes to the latest version and try again"}
2022-04-05T09:06:05Z    ERROR   controller.runnerreplicaset-controller  Reconciler error        {"reconciler group": "actions.summerwind.dev", "reconciler kind": "RunnerReplicaSet", "name": "org-xxx-gg9z5", "namespace": "actions-runner", "error": "Operation cannot be fulfilled on runners.actions.summerwind.dev \"org-xxx-gg9z5-knxg4\": the object has been modified; please apply your changes to the latest version and try again"}
2022-04-05T09:07:03Z    INFO    actions-runner-controller.runnerpod     Runner has just been unregistered.      {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:03Z    INFO    actions-runner-controller.runnerpod     Runner has just been unregistered.      {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:03Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:05Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:05Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:07:06Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:06Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:07:12Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:12Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:07:21Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:24Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:25Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:25Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:07:30Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:30Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:07:43Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:55Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:07:55Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:08:01Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:08:01Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:08:15Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:08:23Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:08:54Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:08:54Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:08:59Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:08:59Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:09:12Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:09:25Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:10:22Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:10:22Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:10:28Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:10:29Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:10:29Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:10:42Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:11:30Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:12:32Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:13:18Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:13:18Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:13:23Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:13:23Z    DEBUG   actions-runner-controller.runner        Runner appears to have been registered and running.     {"runner": "actions-runner/org-xxx-gg9z5-knxg4", "podCreationTimestamp": "2022-04-05 09:06:03 +0000 UTC"}
2022-04-05T09:13:34Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:13:35Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:14:36Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:15:38Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:16:40Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:17:42Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
2022-04-05T09:18:31Z    INFO    actions-runner-controller.runnerpod     Runner pod is marked as already unregistered.   {"runnerpod": "actions-runner/org-xxx-gg9z5-knxg4"}
<this pattern repeats>
```

partial log from runner container (some of this may be out of order)
```
2022-04-05 09:06:04.194	[0;97mWaiting until Docker is avaliable or the timeout is reached[0m
2022-04-05 09:06:04.194	[0;97mDocker enabled runner detected and Docker daemon wait is enabled[0m
2022-04-05 09:06:07.372	CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
2022-04-05 09:06:07.375	[0;97mGithub endpoint URL https://github.com/[0m
2022-04-05 09:06:07.943	Passing --ephemeral to config.sh to enable the ephemeral runner.
2022-04-05 09:06:07.944	[0;97mConfiguring the runner.[0m
2022-04-05 09:06:07.944	Passing --disableupdate to config.sh to disable automatic runner updates.
2022-04-05 09:06:08.256	--------------------------------------------------------------------------------
2022-04-05 09:06:08.256	|                                                                              |
2022-04-05 09:06:08.256	|                       Self-hosted runner registration                        |
2022-04-05 09:06:08.256	|                                                                              |
2022-04-05 09:06:08.256	|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
2022-04-05 09:06:08.256	|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
2022-04-05 09:06:08.256	|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
2022-04-05 09:06:08.256	|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
2022-04-05 09:06:08.256	|        ____ _ _   _   _       _          _        _   _                      |
2022-04-05 09:06:08.256	--------------------------------------------------------------------------------
2022-04-05 09:06:08.256
2022-04-05 09:06:08.257
2022-04-05 09:06:08.257	# Authentication
2022-04-05 09:06:08.257
2022-04-05 09:06:10.111	√ Connected to GitHub
2022-04-05 09:06:10.111
2022-04-05 09:06:10.222
2022-04-05 09:06:10.222	# Runner Registration
2022-04-05 09:06:10.222
2022-04-05 09:06:10.354
2022-04-05 09:06:10.354
2022-04-05 09:06:10.355
2022-04-05 09:06:10.685	√ Runner successfully added
2022-04-05 09:06:12.341
2022-04-05 09:06:12.341	# Runner settings
2022-04-05 09:06:12.341
2022-04-05 09:06:12.341	√ Runner connection is good
2022-04-05 09:06:12.347
2022-04-05 09:06:12.347	√ Settings Saved.
2022-04-05 09:06:12.347
2022-04-05 09:06:12.389	[0;32mRunner successfully configured.[0m
2022-04-05 09:06:12.390	  "workFolder": "/runner/_work"
2022-04-05 09:06:12.390	  "gitHubUrl": "https://github.com/<redacted>",
2022-04-05 09:06:12.390	  "serverUrl": "https://pipelines.actions.githubusercontent.com/<redacted>",
2022-04-05 09:06:12.390	  "ephemeral": true,
2022-04-05 09:06:12.390	  "disableUpdate": true,
2022-04-05 09:06:12.390	  "poolName": "Default",
2022-04-05 09:06:12.390	  "poolId": 1,
2022-04-05 09:06:12.390	  "agentName": "org-xxx-gg9z5-knxg4",
2022-04-05 09:06:12.390	  "agentId": 38266,
2022-04-05 09:06:12.390	{
2022-04-05 09:06:14.175
2022-04-05 09:06:14.175	√ Connected to GitHub
2022-04-05 09:06:14.175	}
2022-04-05 09:06:14.649	Current runner version: '2.289.2'
2022-04-05 09:06:14.650	2022-04-05 09:06:14Z: Listening for Jobs
2022-04-05 09:07:05.021	An error occurred: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
2022-04-05 09:07:24.544	[0;97mWaiting until Docker is avaliable or the timeout is reached[0m
2022-04-05 09:07:24.544	[0;97mDocker enabled runner detected and Docker daemon wait is enabled[0m
2022-04-05 09:07:24.608	CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
2022-04-05 09:07:24.611	[0;97mGithub endpoint URL https://github.com/[0m
2022-04-05 09:07:26.882	[0;97mConfiguring the runner.[0m
2022-04-05 09:07:26.882	Passing --disableupdate to config.sh to disable automatic runner updates.
2022-04-05 09:07:26.882	Passing --ephemeral to config.sh to enable the ephemeral runner.
2022-04-05 09:07:27.295	|                                                                              |
2022-04-05 09:07:27.295	|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
2022-04-05 09:07:27.295	|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
2022-04-05 09:07:27.295	|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
2022-04-05 09:07:27.295	|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
2022-04-05 09:07:27.295	|        ____ _ _   _   _       _          _        _   _                      |
2022-04-05 09:07:27.295	--------------------------------------------------------------------------------
2022-04-05 09:07:27.295
2022-04-05 09:07:27.296	--------------------------------------------------------------------------------
2022-04-05 09:07:27.296	|                                                                              |
2022-04-05 09:07:27.296	|                       Self-hosted runner registration                        |
2022-04-05 09:07:27.309	Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.
2022-04-05 09:07:27.317	[0;32mRunner successfully configured.[0m
2022-04-05 09:07:27.318	  "workFolder": "/runner/_work"
2022-04-05 09:07:27.318	  "gitHubUrl": "https://github.com/<redacted>",
2022-04-05 09:07:27.318	  "serverUrl": "https://pipelines.actions.githubusercontent.com/<redacted>",
2022-04-05 09:07:27.318	  "ephemeral": true,
2022-04-05 09:07:27.318	  "disableUpdate": true,
2022-04-05 09:07:27.318	  "poolName": "Default",
2022-04-05 09:07:27.318	  "poolId": 1,
2022-04-05 09:07:27.318	  "agentName": "org-xxx-gg9z5-knxg4",
2022-04-05 09:07:27.318	  "agentId": 38266,
2022-04-05 09:07:27.318	{
2022-04-05 09:07:27.321	mv: cannot move './externalstmp/node16_alpine' to './externals/node16_alpine': File exists
2022-04-05 09:07:27.321	mv: cannot move './externalstmp/node16' to './externals/node16': File exists
2022-04-05 09:07:27.321	mv: cannot move './externalstmp/node12_alpine' to './externals/node12_alpine': File exists
2022-04-05 09:07:27.321	mv: cannot move './externalstmp/node12' to './externals/node12': File exists
2022-04-05 09:07:29.095
2022-04-05 09:07:29.095	√ Connected to GitHub
2022-04-05 09:07:29.095	}
2022-04-05 09:07:29.584	Failed to create a session. The runner registration has been deleted from the server, please re-configure.
<and pattern repeats>
```

It seems like there's maybe something missing in the controller to deal with pods that get into a crash looping state, and delete them.

**Comment by AchalaDias** [comment] 2022-04-05 12:33
Same thing happening to me also. I have scheduled 50 runners in in the cluster but some of runners are in crashloop with error `Failed to create a session. The runner registration has been deleted from the server, please re-configure`.

This started happen when I redeployed the runners with latest image tag.

**Comment by danxmoran** [comment] 2022-04-05 14:03
I also see pods fall into a crash-loop when using v0.22.x, though with a different error:
```
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 (Not Found).
Configuration failed. Retrying
Configuration failed!
```
(the above repeats many times within a single run before giving up)


I don't think it's an auth/configuration problem on our end, because other pods within the same `RunnerDeployment` boot up without problems.

**Comment by toast-gear** [comment] 2022-04-06 10:48
`Failed to create a session. The runner registration has been deleted from the server, please re-configure` seems to occure when a runner is de-registered but the `.runner` file is retained [[1]](https://github.com/actions/runner/issues/1337). @cspargo are you doing anything with volumes / devices which might impact the runner software from being able to remove its `.runner` file as part of the de-registration process as controlled by the `--ephemeral` flag?

**Comment by lovesegfault** [comment] 2022-04-07 00:00
This happens to me too, and it's pretty bad because you can get in a situation like this:
1. The cluster scales down to a few runners (e.g. 2)
2. Load is low, no scale-up event occurs
3. The two runners run into this issue, leaving them in a `CrashLoopBackoff`
4. The `PercentageRunnersBusy` metric sees no busy runners
5. Despite pending actions piling up, the cluster doesn't scale
6. CI stops working

Had this happen to me today, luckily I noticed before it caused major issues. I had to manually intervene and delete the `CrashLoopBackoff` pods for things to go back to normal.

Perhaps `PercentageRunnersBusy` should consider crashed runners as busy?

**Comment by kitsirota** [comment] 2022-04-13 17:53
+1 We are now running into the same issues with crash loops on a seemly random set of runners each time.  I am not a huge fan of removing the ephemeral flag, but without a workaround we might have to re-use pods which may lead to other issues down the line.

**Comment by mumoshu** [comment] 2022-06-06 00:09
@lovesegfault Hey! Still curious, but did you actually see the same error, `Failed to create a session. The runner registration has been deleted from the server` in your runner logs when it happened? 🤔

**Comment by mumoshu** [comment] 2022-06-06 00:17
@cspargo @lovesegfault Would you mind sharing the output from `kubectl get po -o yaml` on a crash-looping pod so that I can better understand what's going on?

The context is that ARC already has a logic to detect runner pods that are timed out while waiting for registration and it's somehow not working. Probably we'd need to consult `kubectl get po -o yaml` output and see what's missing in the condition.

**Comment by dani-newman** [comment] 2022-06-12 13:49
Same here.

**Comment by mumoshu** [comment] 2022-06-15 02:20
@AchalaDias @dani-newman @lovesegfault What's your ARC version? I now remember that I've already fixed this in 0.24.0 by changing the default runner pod restartPolicy to Never (previously it was OnFailure so it ended up restarting forever and ARC waited until it finally comes up, which in this case never happens)

**Comment by dani-newman** [comment] 2022-06-15 15:54
@mumoshu yup, that was the version issue. Thank you!

**Comment by lovesegfault** [comment] 2022-06-15 16:50
I haven't been able to reproduce this in a while, I think it's safe to consider it fixed :)

**Comment by mumoshu** [comment] 2022-06-23 00:45
Thanks for confirming! I'm closing this as resolved. If anyone is encountering this in a future version of ARC, almost certainly it's another bug with the same surface. Please open a dedicated issue rather than commenting on this 🙏

**Closed by mumoshu** 2022-06-23 00:45 UTC
Labels: bug
